// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpcsqJfJtYxENesbBfqpcEmGzqsdMIyzQ',
    appId: '1:349811031598:web:0464fe2d384b39290369bf',
    messagingSenderId: '349811031598',
    projectId: 'lab345',
    authDomain: 'lab345.firebaseapp.com',
    storageBucket: 'lab345.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwFBE7GWXh5BYMf_I9JAu_deOCZV1rPpU',
    appId: '1:349811031598:android:8e063ef06906b9b00369bf',
    messagingSenderId: '349811031598',
    projectId: 'lab345',
    storageBucket: 'lab345.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAILHQ2jQaiyMj-pesjXdvAWMIovaBIlbs',
    appId: '1:349811031598:ios:67ef23fed407f8780369bf',
    messagingSenderId: '349811031598',
    projectId: 'lab345',
    storageBucket: 'lab345.appspot.com',
    iosBundleId: 'com.example.lab345',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAILHQ2jQaiyMj-pesjXdvAWMIovaBIlbs',
    appId: '1:349811031598:ios:62264b1b16d8e6610369bf',
    messagingSenderId: '349811031598',
    projectId: 'lab345',
    storageBucket: 'lab345.appspot.com',
    iosBundleId: 'com.example.lab345.RunnerTests',
  );
}
